eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://host.docker.internal:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: comment-user
  data:
    mongodb:
      host: host.docker.internal

      port: 27017
  cloud:
    discovery:
      enabled: true
server:

management:
  endpoints:
    web:
      exposure:
        include: '*'





